# Generated by Django 6.0.4 on 2026-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
