# Generated by Django 5.0.6 on 2026-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flat_lat_flat_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flat',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
