# Generated by Django 5.0.6 on 2026-04-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bed_price_flat_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/'),
        ),
    ]
