# Generated by Django 5.0.6 on 2026-04-13 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tenant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='joined_at',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
